### PR TITLE
Demo README: review, edit, and include attack sketch from issue #26

### PR DESCRIPTION
**Pull request by vladimir-v-diaz**
Edits to text after following the instructions, running the demo, and adding additional attacks.

### CODE REVIEW

**Comment by vladimir-v-diaz** [comment]
Should we make it clear how users can start the Python interpreter and enter commands on the Python (>>>) prompt? Not everyone trying out the reference implementation might be familiar with Python.

**Comment by vladimir-v-diaz** [comment]
I am moving this PR from awwad/uptane

**Comment by vladimir-v-diaz** [comment]
@awwad 
The README has been edited to include your review comments and requests.  Its companion pull request #45 (that adds attack and miscellaneous functions needed by the demo) is also ready to be reviewed.

**Comment by awwad** [comment]
This is good, thanks. (:

I've made a bunch of revisions to this and PR #45 and will push them together shortly.

**Pull request merged**
