### PR TITLE
Better sample data

### PR DESCRIPTION
**Pull request by awwad**
- Add JSON sample data (instead of only DER samples)
- Add the automatically-gzipped metadata files. (TUF optionally gzips each metadata file.)
- Update the full metadata zips to include these and the other new long-expiry data.

Merge #107 first, then rebase this (will remove 577ab5d from this PR)

### CODE REVIEW

**Comment by heartsucker** [comment]
I've been working on this for work: https://github.com/heartsucker/uptane-test-vectors.

They don't have human friendly names, but it might be useful to add these in some capacity (possibly as a git submodule).

**Comment by awwad** [comment]
Thanks (: I'll take a look.

**Comment by awwad** [comment]
The repo you have there is along the lines of what we're thinking for [TAP 7](https://github.com/theupdateframework/taps/blob/master/tap7.md) - and the eventual Uptane extension of it - yes! These particular files, added in this PR, are intended only as samples and not compliance testing data. I do use them in some unit tests for the secondary module, though.

**Comment by awwad** [comment]
BTW, FYI, @vladimir-v-diaz, [that format](https://github.com/heartsucker/uptane-test-vectors) may be of use for TUF's compliance tests.

**Comment by vladimir-v-diaz** [comment]
Yep!

Note that the link you provided is broken.  It incorrectly has a period at the end.

((Seb edit: Fixed, thanks!))

**Comment by heartsucker** [comment]
@awwad Got it. Carry on, then. :D

**Comment by vladimir-v-diaz** [comment]
Should you also add the gzipped versions of JSON metadata?

What metadata formats are stored in the full metadata zips?  role.der; role.der.gz; role.json, role.json.gz?

**Comment by awwad** [comment]
I think they're all in there, in the folders and the zip files.

4 files per role (4 roles) per repository (2 repositories) per scenario (2 scenarios), the four files being: .json, .der, .json.gz, .der.gz.

**Comment by vladimir-v-diaz** [comment]
I do not see the addition of gzipped JSON files, only `.der.gz`.  Are you only including them in the full metadata zip?

**Comment by awwad** [comment]
`:facepalm`

`*.json.gz` was in the .gitignore (and also my global gitignore). Sorry, fixed in 4d75719. Thanks for noticing early. (:

**Pull request merged**
